using CatalogTopics.Entities;
using MongoDB.Driver;

namespace CatalogTopics.Data
{
    public class TopicsContextSeed
    {
        public static void SeedData(IMongoCollection<Topic> TopicCollection)
        {
            var existTopic = TopicCollection.Find(p => true).Any();
            if (!existTopic)
            {
                TopicCollection.InsertManyAsync(GetPreconfiguredTopics());
            }
        }

        private static IEnumerable<Topic> GetPreconfiguredTopics()
        {
            return new List<Topic>()
            {
                //mislim da ce id biti generated by default
                new Topic()
                {
                    TopicName="Geography" 
                },
                new Topic()
                {
                    TopicName="History"
                },
                new Topic()
                {
                   TopicName="Biology"
                },
                 new Topic()
                {
                   TopicName="Art&Music"
                },
                  new Topic()
                {
                   TopicName="GeneralQuiz"
                }
            };
        }
    }
}